version: '2'
services:
  proceil-app:
    image: proceil
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://proceil-postgresql:5432/proceil
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  proceil-postgresql:
    extends:
      file: postgresql.yml
      service: proceil-postgresql
